version: "3.8"
services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
  api_server:
    image: api-server
    ports: 
      - '3001:3001'
  mongo:
    image: mongo:3.6.19-xenial





    # volumes:
    #   - ./frontend:/app
    #   - ./app/node_modules 